Repository Satellite-im/UplinkWeb, pull requests merged in 2024-12, with the labels that each got.

#902 chore(release): 2.0.5
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/lib/config.ts
  src/routes/settings/about/+page.svelte
Labels: Missing dev review

#894 fix(Storage): Fix upload files on mobile for storage
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Requested Changes

#903 fix(ui): Update InstallBanner to hide on mobile devices
  src/lib/components/ui/InstallBanner.svelte
Labels: Missing dev review

#904 fix(ui): Update InstallBanner to hide on mobile devices
  src/lib/components/ui/InstallBanner.svelte
Labels: Missing dev review

#905 fix(Banner): Avoid banner on mobile apps, fix show correct button for iPhone
  package.json
  src/lib/components/ui/InstallBanner.svelte
  src/lib/utils/Mobile.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Approved

#897 fix(Mobile): Fix copy did on friends page in mobile
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Approved

#899 fix(Mobile): Add a correct check to show or not keybinds section
  android/app/capacitor.build.gradle
  src/routes/settings/+layout.svelte
Labels: Missing dev review, QA Approved

#896 feat(mobile): add device detection and screen orientation locking to portrait
  android/app/capacitor.build.gradle
  src/routes/+layout.svelte
Labels: QA Approved

#895 fix(Mobile): Fix context menu on storage with long press
  src/lib/components/ui/ContextMenu.svelte
Labels: Missing dev review, QA Approved

#921 chore(doc): Update README.md
  README.md
Labels: Missing dev review

#923 chore(fix): fix bug profile
  src/lib/components/ui/ContextMenu.svelte
Labels: being tested

#924 feat(Mobile-Android): Paint android safe areas
  android/app/src/main/java/com/uplink/app/MainActivity.java
  android/app/src/main/java/com/uplink/plugins/SafeAreaColorPlugin.java
  src/lib/plugins/safeAreaColorAndroid.ts
  src/lib/utils/Mobile.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Approved

#927 chore(docs): Update README.md with instructions to show android logs
  README.md
Labels: Missing dev review

#925 feat(App): Improve sidebar animation
  src/lib/components/ui/Modal.svelte
  src/lib/globals/animations.ts
  src/lib/layouts/Sidebar.svelte
Labels: Missing dev review, QA Approved

#938 update(vite): use alias for service worker dir
  src/serviceworker/index.ts
  vite.config.js
Labels: being tested

#926 fix(Navigation): Improve navigation using bottom nav bar on mobile
  src/lib/enums/index.ts
  src/lib/layouts/BottomNavBarMobile.svelte
  src/routes/+layout.svelte
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
  src/routes/friends/+page.svelte
  src/routes/settings/+layout.svelte
Labels: QA Approved, 🫡 Dev Approved Review

#943 update(ci): upgrade docker image on tests
  .github/workflows/automated-tests.yml
Labels: Waiting for CI

#945 update(ci): remove temp reference
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#946 chore(release): 2.0.6
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/lib/config.ts
  src/routes/settings/about/+page.svelte
Labels: Missing dev review

#935 feat(community): Add Communities api
  package.json
  src/lib/layouts/Chatbar.svelte
  src/lib/wasm/CommunitiesStore.ts
  src/lib/wasm/RaygunStore.ts
Labels: being tested

#942 feat(share): add share functionality for backup seed phrase on mobile
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  src/lib/lang/en.json
  src/lib/layouts/login/RecoveryCopy.svelte
Labels: question, Missing dev review

#937 fix(ContextMenu): Fix context menu on iOS with long press
  src/lib/components/ui/ContextMenu.svelte
Labels: QA Approved, 🫡 Dev Approved Review

#948 fix(WhiteScreen): Configure launch duration and auto-hide settings
  capacitor.config.ts
Labels: Missing dev review, QA Approved

#944 fix(Mobile): Fix download files from storage
  ios/App/App/Info.plist
  ios/App/PrivacyInfo.xcprivacy
  src/lib/lang/en.json
  src/lib/wasm/ConstellationStore.ts
  src/routes/files/+page.svelte
Labels: QA Approved, 🫡 Dev Approved Review

#956 update(friends): make add friend input visible on mobile
  src/lib/lang/en.json
  src/routes/friends/+page.svelte
Labels: Missing dev review

#953 fix(Mobile): Fix camera on calls
  capacitor.config.ts
Labels: Missing dev review

#893 feat(wasm): Import/export account
  src/lib/components/settings/OrderedPhrase.svelte
  src/lib/elements/Input/FileInput.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/lang/en.json
  src/lib/layouts/login/Entrypoint.svelte
  src/lib/layouts/login/ImportAccount.svelte
  src/lib/layouts/login/Unlock.svelte
  src/lib/wasm/HandleWarpErrors.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/auth/+page.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, 🔒 blocked

#958 chore(import): hide import remote
  src/lib/lang/en.json
  src/lib/layouts/login/ImportAccount.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#960 chore(release): 2.0.7
  android/app/capacitor.build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/lib/config.ts
  src/routes/settings/about/+page.svelte
Labels: Missing dev review

#962 chore(typos): fix typos
  src/lib/wasm/CommunitiesStore.ts
  src/routes/wallet/+page.svelte
Labels: QA Approved, 🫡 Dev Approved Review

#967 chore(release): 2.0.8
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/lib/config.ts
  src/routes/settings/about/+page.svelte
Labels: Missing dev review

#968 chore(android): add url
  src/lib/config.ts
Labels: Missing dev review

#964 fix(iOS): Avoid zoom on iOS mobile app when tap on input elements
  src/lib/elements/Input/Input.svelte
Labels: Missing dev review, QA Approved, Failed Automated Test

#959 feat(chat): implement file sharing and downloading functionality for files in chats
  src/lib/components/messaging/embeds/FileEmbed.svelte
  src/lib/utils/Functions.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Approved

#963 fix(iOS): Fix chatbar when use sidebar
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Approved

#965 fix(Android): Fix back button on android
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  src/routes/+layout.svelte
Labels: Missing dev review, QA Approved
