Repository Satellite-im/UplinkWeb, pull requests merged in 2024-06, with the labels that each got.

#49 add(attributes): add test attributes for banner and copy id buttons
  src/lib/components/ui/ContextMenu.svelte
  src/routes/friends/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#50 add(attributes): add attributes for toast and select of profile
  src/lib/elements/Toast.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#52 add(attributes): add hooks and data-cy attributes for settings pages
  src/lib/components/inventory/InventoryItem.svelte
  src/lib/components/profile/ProfilePicture.svelte
  src/lib/components/ui/ColorSwatch.svelte
  src/lib/components/ui/PopupButton.svelte
  src/routes/settings/inventory/+page.svelte
  src/routes/settings/messages/+page.svelte
  src/routes/settings/preferences/+page.svelte
Labels: Missing dev review

#54 update(attribute): update test attribute for context menu options
  src/lib/components/ui/ContextMenu.svelte
Labels: Missing dev review

#55 fix(files): Fix creating nested folders and sidebar fix for new folders
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
Labels: Missing dev review, QA Tested

#58 add(ci): add cypress tests execution workflow on pr commits
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#56 feat(Constellation): Upload and remove files
  package-lock.json
  package.json
  src/lib/components/files/FileFolder.svelte
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/routes/files/+page.svelte
  yarn.lock
Labels: Missing dev review

#61 chore(typos): fix typos
  src/lib/enums/index.ts
  src/lib/lang/index.ts
  src/lib/state/settings/default.ts
  src/lib/state/settings/index.ts
  src/routes/settings/+layout.svelte
  src/routes/settings/accessability/+page.svelte
Labels: Missing dev review

#75 add(attributes): add test attributes for settings audio and extentsions
  src/lib/components/settings/Key.svelte
  src/lib/components/settings/Meter.svelte
  src/lib/components/settings/VideoTest.svelte
  src/lib/components/ui/Banner.svelte
  src/lib/components/ui/RelaySelector.svelte
  src/lib/elements/UnderConstruction.svelte
  src/routes/settings/about/+page.svelte
  src/routes/settings/audio_video/+page.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/extensions/+page.svelte
  src/routes/settings/keybinds/+page.svelte
  src/routes/settings/licenses/+page.svelte
  src/routes/settings/notifications/+page.svelte
Labels: Missing dev review, QA Tested

#88 chore(Files): remove unused code & added icon property.
  src/routes/files/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#91 Files patch
  src/lib/elements/Text.svelte
Labels: Missing dev review, Invalid PR title

#90 chore(lint): add svelte-check to find errors
  package-lock.json
  package.json
  yarn.lock
Labels: Missing dev review

#92 Doc
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
Labels: Missing dev review, Invalid PR title

#93 chore(fix): fix error on empty status message
  src/lib/wasm/MultipassStore.ts
Labels: Missing dev review

#95 update(fix): fix svelte check errors
  src/lib/components/messaging/embeds/brands/SpotifyEmbed.svelte
  src/lib/components/ui/ContextMenu.svelte
  src/lib/components/ui/EmojiGroup.svelte
  src/lib/enums/index.ts
  src/lib/lang/index.ts
  src/lib/media/Voice.ts
  src/lib/mock/community.ts
  src/lib/state/Store.ts
  src/lib/types/index.ts
  src/lib/utils/Logger.ts
  src/lib/utils/Notes.ts
  src/lib/utils/Result.ts
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/lib/wasm/IWarp.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/chat/+page.svelte
  src/routes/pre/+page.svelte
Labels: Missing dev review

#83 fix(bug): can't login without clearing cache
  src/lib/wasm/TesseractStore.ts
Labels: Missing dev review, Missing fixing conflict, Changes Requested

#100 fix(bug): logger functions missing
  src/lib/components/ui/ContextMenu.svelte
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/utils/Logger.ts
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/routes/+layout.svelte
  src/routes/auth/new_account/+page.svelte
  src/routes/chat/+page.svelte
  src/routes/developer/debug/voice/+page.svelte
  src/routes/friends/+page.svelte
Labels: Missing dev review

#98 update(Multipass): Improve login proccess
  package-lock.json
  package.json
  src/lib/components/PinInput.svelte
  src/lib/state/auth/index.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/auth/unlock/+page.svelte
  src/routes/settings/profile/+page.svelte
  yarn.lock
Labels: Missing dev review, QA Tested

#51 feat(raygun): Add Raygun store
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/messaging/message/MessageReactions.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/components/ui/ContextMenu.svelte
  src/lib/components/ui/EmojiGroup.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/state/Store.ts
  src/lib/state/conversation/index.ts
  src/lib/state/ui/index.ts
  src/lib/types/index.ts
  src/lib/utils/CancellablePromise.ts
  src/lib/utils/Result.ts
  src/lib/wasm/EnumParser.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
  src/routes/friends/+page.svelte
Labels: Ready to Merge

#96 fix(devmode): fix devmode nav and long file names
  src/lib/components/files/FileFolder.svelte
  src/lib/components/files/ImageFile.svelte
  src/lib/mock/files.ts
  src/lib/types/index.ts
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/developer/+page.svelte
Labels: Ready to Merge

#101 feat(various): PPT, PTM, PTD - add push to talk, deafen, and mute
  src/lib/components/ui/KeyboardListener.svelte
  src/lib/components/utils/Sounds.ts
  src/lib/enums/index.ts
  src/lib/state/settings/default.ts
  src/lib/types/index.ts
  src/routes/+layout.svelte
  src/routes/settings/keybinds/+page.svelte
  static/assets/mp3/press.mp3
  static/assets/mp3/release.mp3
Labels: Missing dev review, Missing fixing conflict

#103 feat(raygun): implement missing raygun hooks
  package-lock.json
  package.json
  src/lib/wasm/RaygunStore.ts
  yarn.lock
Labels: Ready to Merge

#105 Lingo update
  src/lib/enums/index.ts
Labels: Missing dev review, Invalid PR title

#107 feat(Constellation): Implement download files
  src/lib/types/index.ts
  src/lib/wasm/ConstellationStore.ts
  src/routes/files/+page.svelte
Labels: Ready to Merge

#116 fix(wasm): enable warp persistence
  src/lib/wasm/WarpStore.ts
Labels: Ready for Test

#118 fix(sidebar): add ellipsis to long file titles
  src/lib/components/files/FileFolder.svelte
  src/lib/components/files/ImageFile.svelte
  src/lib/types/index.ts
  src/routes/files/FolderItem.svelte
Labels: Missing dev review, QA Tested

#113 feat(wasm): add default relays
  src/lib/components/ui/RelaySelector.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/state/wasm/relays.ts
Labels: Missing dev review, QA Tested

#120 hotfix(Navigation & PFP): Fixes the navigation locking up when userna…
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/MessageGroup.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/layouts/Slimbar.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, Invalid PR title

#115 feat(chat): Pending messages
  src/lib/components/messaging/PendingMessageGroup.svelte
  src/lib/components/messaging/embeds/PendingFileEmbed.svelte
  src/lib/components/messaging/message/PendingMessage.svelte
  src/lib/enums/icons.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/state/conversation/index.ts
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#128 update(Multipass): Add listener to multipass events
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/+layout.svelte
  src/routes/auth/new_account/+page.svelte
  src/routes/auth/unlock/+page.svelte
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Tested

#130 Hotfix 3
  src/lib/wasm/RaygunStore.ts
Labels: Missing dev review, Invalid PR title

#129 add(attributes): add files test attributes
  src/lib/components/files/FileFolder.svelte
  src/lib/components/ui/ContextMenu.svelte
  src/lib/components/ui/ProgressButton.svelte
  src/routes/files/+page.svelte
Labels: Missing dev review

#138 refactor(yarn): remove yarn
  package-lock.json
  yarn.lock
Labels: Missing dev review

#135 fix(Unlock): Fix stay logged option
  src/lib/components/PinInput.svelte
  src/lib/state/auth/index.ts
  src/routes/+layout.svelte
  src/routes/auth/unlock/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#144 Gif
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/state/ui/index.ts
Labels: Missing dev review, Invalid PR title

#146 feat(chat): wrap emojis
  src/lib/components/utils/Emoji.ts
  src/lib/elements/Text.svelte
  src/lib/elements/renderer/HtmlRenderer.svelte
  src/lib/elements/renderer/TextRenderer.svelte
  src/lib/elements/renderer/index.ts
Labels: Missing dev review

#139 feat(ui): Upload + download files chat
  src/lib/components/messaging/embeds/FileEmbed.svelte
  src/lib/components/messaging/embeds/ImageEmbed.svelte
  src/lib/components/messaging/message/PendingMessage.svelte
  src/lib/elements/FileUploadPreview.svelte
  src/lib/elements/Input/FileInput.svelte
  src/lib/elements/index.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/state/conversation/index.ts
  src/lib/types/index.ts
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: QA Tested, Ready to Merge

#148 chore(grammar): fix typo
  src/lib/wasm/HandleWarpErrors.ts
Labels: Missing dev review, QA Tested
