Repository Satellite-im/UplinkWeb, pull requests merged in 2024-05, with the labels that each got.

#15 add file drag drop for files and chat
  src/lib/lang/index.ts
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
Labels: Missing Dev Review, QA Tested

#21 Fix typo
  src/routes/pre/+page.svelte
Labels: QA Tested

#18 feat(chat): implement searchbar for chats
  src/lib/components/index.ts
  src/lib/components/ui/ChatFilter.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/lang/index.ts
  src/lib/layouts/Sidebar.svelte
  src/lib/wasm/tesseract.ts
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: QA Tested

#27 chore(workflows): add permissions for workflows on PRs
  .github/workflows/add-conflicts-label.yml
  .github/workflows/add-label.yml
  .github/workflows/assigned-label.yml
  .github/workflows/avoid-typos.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/remove-labels.yml
Labels: QA Tested

#28 add(test): test attributes of pin screen to elements and components
  src/lib/components/PinInput.svelte
  src/lib/elements/Button.svelte
  src/lib/elements/Label.svelte
  src/lib/elements/Switch.svelte
  src/routes/auth/unlock/+page.svelte
Labels: Missing dev review, QA Tested

#29 add(testattr): fix existing test attr and add more as hook
  src/routes/auth/unlock/+page.svelte
Labels: Missing dev review

#36 add(testid): add test ids for several ui elements working
  src/lib/elements/Checkbox.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/layouts/Navigation.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/layouts/Topbar.svelte
  src/routes/chat/+page.svelte
  src/routes/friends/+page.svelte
Labels: Missing dev review

#41 update(attributes): add attributes for create group modal
  src/lib/components/group/CreateGroup.svelte
Labels: Missing dev review

#34 feat(Multipass): Create new account and added function to update username and status message
  src/lib/elements/Input/Input.svelte
  src/lib/state/Store.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/auth/new_account/+page.svelte
  src/routes/auth/unlock/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#42 add(attributes): add tests attributes for create username screen
  src/lib/elements/Title.svelte
  src/routes/auth/new_account/+page.svelte
Labels: Missing dev review

#32 add(feat): impl toast message system
  src/lib/components/index.ts
  src/lib/components/ui/Toasts.svelte
  src/lib/elements/Button.svelte
  src/lib/elements/Toast.svelte
  src/lib/lang/index.ts
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/state/ui/toast.ts
  src/routes/+layout.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#43 update(Warp): Add test relay server
  package-lock.json
  package.json
  src/lib/wasm/WarpStore.ts
  yarn.lock
Labels: Missing dev review

#46 add(test): test attributes for settings profile page
  src/lib/components/settings/OrderedPhrase.svelte
  src/lib/components/ui/FileUploadButton.svelte
  src/lib/elements/Checkbox.svelte
  src/lib/elements/Select.svelte
  src/lib/layouts/SettingSection.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#47 feat(files): Folder Traversal w/ link to sidebar file tree
  src/lib/components/files/FileFolder.svelte
  src/lib/enums/icons.ts
  src/lib/layouts/Sidebar.svelte
  src/lib/mock/files.ts
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/types/index.ts
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
Labels: Missing dev review
