Repository Satellite-im/UplinkWeb, pull requests merged in 2024-08, with the labels that each got.

#340 add(reporter): add allure report for CI automated tests
  .github/workflows/automated-tests.yml
Labels: Missing dev review, Draft

#338 chore(github): display hash from latest commit on about page
  .gitignore
  package.json
  scripts/write-commit-hash.cjs
  src/app.d.ts
  src/routes/settings/about/+page.svelte
  svelte.config.js
  vite.config.js
Labels: Missing dev review, QA Tested

#349 update(fix): friend request not updating realtime
  src/lib/layouts/Navigation.svelte
  src/lib/state/Store.ts
  src/routes/friends/+page.svelte
Labels: QA Tested

#351 fix(App): Fix black screen when refresh
  src/routes/+layout.svelte
Labels: Missing dev review

#361 feat(Better Polling & loading): General fixes to polling and loading status for many components
  src/app.scss
  src/lib/components/Polling.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/Conversation.svelte
  src/lib/elements/Loader.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, Invalid PR title

#356 fix(settings): Fix banner/profile reset on changes
  src/lib/state/Store.ts
  src/lib/wasm/MultipassStore.ts
  src/routes/auth/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#355 fix(Favorites): Fix profile picture on favorites
  src/lib/layouts/Slimbar.svelte
Labels: Missing dev review, QA Tested

#346 add(test): test attributes for settings pages and files
  src/lib/components/ui/CDNConfigurator.svelte
  src/lib/components/ui/GamepadListener.svelte
  src/lib/components/ui/IntegrationDisplay.svelte
  src/lib/components/widgets/BatteryIndicator.svelte
  src/lib/components/widgets/CPU.svelte
  src/lib/components/widgets/RamUsage.svelte
  src/lib/components/widgets/WidgetBar.svelte
  src/lib/elements/RangeSelector.svelte
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/gamepad/+page.svelte
  src/routes/settings/messages/+page.svelte
  src/routes/settings/preferences/+page.svelte
  src/routes/settings/profile/+page.svelte
  src/routes/settings/realms/+page.svelte
Labels: Missing dev review, QA Tested

#363 fix(Chats): Fixed syncing chats and call control when no chats
  src/lib/components/messaging/Conversation.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#359 update(fix): fix chat preview context menu text for hide chat
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#348 feat(toast): impl clickable toasts
  src/lib/components/ui/Toasts.svelte
  src/lib/elements/Toast.svelte
  src/lib/state/Store.ts
  src/lib/state/ui/toast.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/friends/+page.svelte
  src/routes/wallet/+page.svelte
Labels: QA Tested

#354 fix(Profile): Avoid save changes when click on cancel button on profile page
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#364 feat(chats): Typing indicator
  src/lib/components/Polling.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/lang/en.json
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/mock/users.ts
  src/lib/state/conversation/index.ts
  src/lib/state/db/persistedState.ts
  src/lib/state/ui/index.ts
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: checking stuff

#370 chore(typo): fix typo on log
  src/lib/media/Voice.ts
Labels: Waiting for CI

#369 chore(btc): hide send btc section
  src/lib/layouts/Profile.svelte
Labels: Missing dev review, QA Tested, Failed Automated Test

#372 feat(chat): add reaction indicator
  src/lib/components/messaging/message/MessageReactions.svelte
Labels: Waiting for CI

#376 fix(Styling): Fix weird styling for generic integration kinds
  src/lib/components/inventory/InventoryItem.svelte
  src/lib/lang/en.json
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#380 Hotfix 6
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/index.ts
  src/lib/components/ui/KeyboardListener.svelte
  src/lib/components/ui/MouseListener.svelte
  src/lib/enums/index.ts
  src/lib/media/Voice.ts
  src/lib/state/ui/index.ts
  src/lib/utils/Wallet.ts
  src/lib/wasm/ConstellationStore.ts
  src/routes/+layout.svelte
Labels: Missing dev review, Invalid PR title

#388 Revert "feat(chats): Typing indicator"
  src/lib/components/Polling.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/lang/en.json
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/mock/users.ts
  src/lib/state/conversation/index.ts
  src/lib/state/db/persistedState.ts
  src/lib/state/ui/index.ts
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review

#386 fix(bug): fix copy seed
  src/routes/settings/profile/+page.svelte
Labels: QA Tested, Ready to Merge

#387 fix(picker): fix emoji prop for picker to open on correct tab
  src/lib/lang/en.json
Labels: Missing dev review, QA Tested

#389 feat(chats): Typing indicator
  src/lib/components/Polling.svelte
  src/lib/components/community/settings/CommunitySettings.svelte
  src/lib/components/community/settings/permissions/PermissionsSettings.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/lang/en.json
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/mock/users.ts
  src/lib/state/Store.ts
  src/lib/state/conversation/index.ts
  src/lib/state/db/persistedState.ts
  src/lib/state/ui/index.ts
  src/lib/types/community.ts
  src/lib/types/index.ts
  src/lib/utils/Functions.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
  static/assets/mp3/disconnect.mp3
  static/assets/mp3/request.mp3
  static/assets/mp3/select.mp3
  static/assets/mp3/toast.mp3
Labels: being tested, Failed Automated Test

#402 fix(chat): fix typing indicator
  src/routes/chat/+page.svelte
Labels: Missing dev review, Changes Requested

#409 fix(chat): fix active chat not updating
  src/lib/state/ui/index.ts
Labels: Missing dev review, QA Tested

#415 chore(typo): fix typo
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
Labels: Missing dev review, QA Tested

#418 fix(Files): Fix files not appearing after a refresh
  src/routes/files/+page.svelte
Labels: QA Tested, Failed Automated Test

#417 feat(Chat): Possible to unhide chats
  src/lib/state/Store.ts
  src/lib/state/ui/index.ts
Labels: Ready to Merge

#414 fix(notification): add extra check for multichat notification
  src/lib/wasm/RaygunStore.ts
Labels: Ready to Merge, Failed Automated Test

#416 feat(Storage): Show images thumb on files
  package.json
  src/lib/components/files/FileFolder.svelte
  src/lib/types/index.ts
  src/routes/files/+page.svelte
Labels: Ready to Merge

#435 chore(docs): update asset location
  README.md
  static/logo.png
Labels: Missing dev review

#441 chore(revert): revert wasm version
  package.json
Labels: QA Tested, Waiting for CI

#443 chore(docs): minor update
  README.md
Labels: Missing dev review, QA Tested

#439 fix(Call): Fix float video on screen
  src/lib/components/calling/VideoPreview.svelte
Labels: Missing dev review, QA Tested

#437 fix(Call): Fix float video when user deactivate it
  src/lib/components/calling/VideoPreview.svelte
Labels: Missing dev review, QA Tested

#444 chore(ci): dont add failed label on publish report issues
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#442 chore(package): ditch package
  package.json
Labels: Missing dev review, QA Tested

#446 feat(Communities): Mock communities settings UI.
  src/lib/components/community/settings/CommunitySettings.svelte
  src/lib/components/community/settings/details/CommunityDetails.svelte
  src/lib/components/community/settings/members/ManageMembers.svelte
  src/lib/components/community/settings/moderation/ModerationSettings.svelte
  src/lib/components/community/settings/permissions/PermissionsContainer.svelte
  src/lib/components/community/settings/permissions/PermissionsSettings.svelte
  src/lib/components/community/settings/roles/CreateRole.svelte
  src/lib/components/community/settings/roles/Role.svelte
  src/lib/components/community/settings/roles/RoleSelector.svelte
  src/lib/components/community/settings/security/SecuritySettings.svelte
  src/lib/components/community/settings/tags/CommunityTag.svelte
  src/lib/components/community/settings/tags/CommunityTags.svelte
  src/lib/components/index.ts
  src/lib/components/ui/PopupButton.svelte
  src/lib/components/ui/Toasts.svelte
  src/lib/defaults/community/Permissions.ts
  src/lib/elements/Icon.svelte
  src/lib/elements/Input/NumberInput.svelte
  src/lib/elements/PermissionSwitch.svelte
  src/lib/elements/Text.svelte
  src/lib/enums/community.ts
  src/lib/enums/icons.ts
  src/lib/enums/index.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Navigation.svelte
  src/lib/layouts/SettingSection.svelte
  src/lib/layouts/SimpleSidebar.svelte
  src/lib/layouts/index.ts
  src/lib/mock/community.ts
  src/lib/types/community.ts
  src/lib/types/index.ts
  src/routes/chat/+page.svelte
  src/routes/community/chat/+page.svelte
  src/routes/settings/preferences/+page.svelte
Labels: Missing dev review, QA Tested, Failed Automated Test

#445 fix(wasm): Wasm fix
  src/lib/wasm/AsyncLock.ts
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/lib/wasm/WarpStore.ts
Labels: Missing dev review, QA Tested

#447 feat(console): Add some color (and stacktrace) to console
  src/lib/utils/Logger.ts
Labels: Missing dev review, QA Tested

#440 fix(context): adjust placements on context menu for low screen resolution
  src/lib/components/ui/ContextMenu.svelte
Labels: Missing dev review, QA Tested

#448 fix(chat): fix sidebar time
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/state/conversation/index.ts
Labels: Missing dev review, QA Tested

#450 add(Icons): Icons 8/22/2024
  src/lib/enums/icons.ts
Labels: Missing dev review, QA Tested

#455 fix(chat): Typing fix
  src/lib/elements/Input/Input.svelte
  src/lib/layouts/Chatbar.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#459 fix(warnings): fix warnings on prod build
  src/app.scss
  src/lib/components/community/settings/roles/Role.svelte
  src/lib/components/inventory/InventoryItem.svelte
Labels: Missing dev review, QA Tested

#460 fix(Call): Close settings and volume menu on call when click outside
  .vscode/settings.json
  src/lib/components/calling/CallScreen.svelte
Labels: Missing dev review

#458 feat(Call): Send message when accept call and end call
  src/lib/lang/en.json
  src/lib/media/Voice.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#457 add(test): test attrs for video call and quick profile
  src/lib/components/calling/CallControls.svelte
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/CallSettings.svelte
  src/lib/components/calling/Participant.svelte
  src/lib/components/calling/VolumeMixer.svelte
  src/lib/layouts/Profile.svelte
Labels: Missing dev review, QA Tested

#449 feat(friends): Add loading user indicator
  src/lib/components/friends/Friend.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/state/Store.ts
  src/lib/types/index.ts
  src/lib/wasm/MultipassStore.ts
  src/routes/settings/preferences/+page.svelte
Labels: Missing dev review

#462 Call embeds
  src/lib/components/calling/CallEvents.svelte
  src/lib/components/community/settings/members/ManageMembers.svelte
  src/lib/components/index.ts
  src/lib/enums/icons.ts
  src/lib/enums/index.ts
  src/lib/utils/Functions.ts
  src/routes/chat/+page.svelte
  src/routes/settings/developer/+page.svelte
Labels: Failed Automated Test

#452 fix(files): disable creation of empty name folder
  src/lib/components/files/FileFolder.svelte
  src/routes/files/+page.svelte
Labels: Missing dev review, Failed Automated Test

#468 fix(Compile): Fix compilling error message
  src/lib/media/Voice.ts
Labels: Missing dev review, QA Tested

#464 feat(ethereum): add support for requesting ethereum/erc20 payment requests
  README.md
  package.json
  src/lib/components/wallet/CreateTransaction.svelte
  src/lib/lang/en.json
  src/lib/utils/Wallet.ts
  src/routes/chat/+page.svelte
Labels: QA Tested

#478 chore(docs): minor update
  README.md
Labels: Missing dev review

#469 feat(wasm): update package and fr fix
  package.json
  src/lib/wasm/MultipassStore.ts
Labels: Missing dev review, QA Tested

#434 feat(settings): Seed phrase save
  src/lib/elements/Checkbox.svelte
  src/lib/lang/en.json
  src/lib/state/auth/index.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/auth/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#483 Revert "feat(settings): Seed phrase save"
  src/lib/elements/Checkbox.svelte
  src/lib/lang/en.json
  src/lib/state/auth/index.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/auth/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#484 feat(settings): Seed phrase save
  src/lib/elements/Checkbox.svelte
  src/lib/lang/en.json
  src/lib/state/auth/index.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/auth/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review

#477 chore(test): group chats
  package.json
  src/app.scss
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/group/ViewMembers.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/elements/renderer/TextRenderer.svelte
  src/lib/enums/index.ts
  src/lib/lang/en.json
  src/lib/layouts/Slimbar.svelte
  src/lib/utils/Functions.ts
  src/routes/chat/+page.svelte
  src/variables.scss
Labels: Missing dev review, QA Tested

#485 add(attributes): test attributes for emoji reactions
  src/lib/components/messaging/message/MessageReactions.svelte
Labels: Missing dev review, QA Tested

#503 chore(docs): update docs
  README.md
Labels: Missing dev review
