Repository Satellite-im/UplinkWeb, pull requests merged in 2024-09, with the labels that each got.

#513 chore(ci): run build preview and compare logs
  .github/workflows/run-build.yml
Labels: Missing dev review, QA Tested

#497 fix(groups): fix chats icon on friends page
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Tested

#515 chore(warning): fix chat settings warning
  src/lib/types/index.ts
Labels: Missing dev review

#489 fix(crypto): decimal amount conversion to bigint
  src/lib/components/wallet/CreateTransaction.svelte
  src/lib/utils/Wallet.ts
Labels: Missing dev review, QA Tested

#504 fix(keybind): keybinds triggering sounds outside of calls
  src/lib/media/Voice.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Tested

#518 chore(warning): fix warp warning
  src/lib/wasm/HandleWarpErrors.ts
Labels: Missing dev review

#516 chore(warning): fix integrations warning
  src/lib/mock/users.ts
Labels: Missing dev review

#510 add(tooltips): add missing tooltips on chat page
  src/lib/elements/Button.svelte
  src/lib/enums/index.ts
  src/lib/lang/en.json
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#506 fix(groups): display error if no group name is added
  src/lib/components/group/CreateGroup.svelte
  src/lib/lang/en.json
Labels: Draft

#505 fix(call): fix call settings modal
  src/lib/components/calling/CallSettings.svelte
Labels: Missing dev review

#501 fix(groups): fix group modal list members
  src/lib/components/group/ViewMembers.svelte
Labels: Missing dev review, QA Tested

#507 fix(profile): fix integrations
  src/lib/state/Store.ts
Labels: Missing dev review, QA Tested

#508 chore(build): fix warnings
  src/lib/wasm/IWarp.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#496 fix(groups): add validation when creating group
  src/lib/components/group/CreateGroup.svelte
  src/lib/lang/en.json
Labels: QA Tested

#522 fix(settings): Fix network page
  src/lib/components/ui/RelaySelector.svelte
Labels: Missing dev review, QA Tested

#488 feat(files): fix file reload missing
  src/lib/wasm/ConstellationStore.ts
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#487 feat(files): delete folders
  src/routes/files/+page.svelte
Labels: blocked

#523 task(GroupChats): Added UI to change the communities photo.
  src/lib/components/group/GroupSettings.svelte
  src/lib/components/group/ViewMembers.svelte
Labels: Missing dev review, QA Tested

#526 feat(chat): Impl emoji button in reaction
  src/lib/components/ui/EmojiGroup.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/state/ui/index.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review

#514 fix(files): File rework
  src/lib/components/files/FileFolder.svelte
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/routes/files/+page.svelte
Labels: Missing dev review

#529 add(attrs): add test attributes for embeds and messages chats
  src/lib/components/messaging/embeds/FileEmbed.svelte
  src/lib/components/messaging/embeds/ImageEmbed.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review

#530 chore(grammar): update copy
  src/routes/files/+page.svelte
Labels: Missing dev review

#531 chore(copy): update copy
  src/lib/wasm/HandleWarpErrors.ts
Labels: Missing dev review

#532 chore(files): fix list layout
  src/routes/files/+page.svelte
Labels: Missing dev review

#533 chore(docs): minor grammar update
  README.md
Labels: Missing dev review

#524 feat(settings): hide seed button if missing
  src/lib/lang/en.json
  src/routes/settings/profile/+page.svelte
Labels: QA Tested, Failed Automated Test

#535 fix(Constellation): Fix message when create item with same name
  src/lib/wasm/HandleWarpErrors.ts
Labels: Missing dev review

#537 feat(Stickers): Send stickers and gifs on chat
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/utils/CommonVariables.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#536 feat(Chat): Convert text into emojis on chatbar when settings for it is enabled
  src/lib/components/market/Market.svelte
  src/lib/components/messaging/emoji/EmojiList.ts
  src/lib/components/messaging/emoji/category/activities.ts
  src/lib/components/messaging/emoji/category/animalsAndNature.ts
  src/lib/components/messaging/emoji/category/flags.ts
  src/lib/components/messaging/emoji/category/foodAndDrink.ts
  src/lib/components/messaging/emoji/category/objects.ts
  src/lib/components/messaging/emoji/category/peopleAndBody.ts
  src/lib/components/messaging/emoji/category/smileysAndEmotion.ts
  src/lib/components/messaging/emoji/category/symbols.ts
  src/lib/components/messaging/emoji/category/travelAndPlaces.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/state/ui/index.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Tested, Missing fixing conflict

#534 update(Group): Improve group chats
  package.json
  src/lib/components/group/GroupSettings.svelte
  src/lib/components/group/ViewMembers.svelte
  src/lib/components/ui/FileUploadButton.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/elements/Switch.svelte
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#540 fix(Chat): Fix chatbar messages to persist through different conversations
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Sidebar.svelte
  src/routes/chat/+page.svelte
Labels: QA Tested, Failed Automated Test

#543 fix(Sidebar): Sort chats on sidebar according with datetime last message sent or received
  src/routes/chat/+page.svelte
Labels: Missing dev review

#542 fix(ChatBar): Rebuild chatbar to align placeholder text
  src/lib/layouts/Chatbar.svelte
Labels: Missing dev review, Failed Automated Test

#544 fix(Chat): Fix remove reaction when user select exactly the same emoji
  src/routes/chat/+page.svelte
Labels: Missing dev review

#545 fix(Files): Fix file name when open OS pop up to download it, it is not showing _
  src/lib/components/messaging/ChatPreview.svelte
  src/routes/files/+page.svelte
Labels: Ready for Test

#548 fix(Chat): Update last message on chat preview when it is edited or removed
  src/lib/state/conversation/index.ts
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
Labels: Missing dev review

#549 fix(Chat): Fix last message edited on sidebar
  src/lib/state/conversation/index.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#551 fix(Chat): Fix remove emoji reaction from message
  src/routes/chat/+page.svelte
Labels: Missing dev review

#554 chore(locale): fix locale
  src/lib/lang/en.json
Labels: Missing dev review

#555 chore(marketplace): hide button
  src/lib/layouts/Sidebar.svelte
Labels: Missing dev review

#558 feat(Install Banner): Added install banner, pending functionality to actually download
  src/app.scss
  src/lib/components/ui/InstallBanner.svelte
  src/lib/elements/Button.svelte
  src/lib/elements/Icon.svelte
  src/lib/enums/icons.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Tested, Failed Automated Test

#561 chore(Release): Hide un-finished features behind devmode
  src/lib/components/messaging/MessageGroup.svelte
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/components/messaging/message/Message.svelte
  src/lib/defaults/routes.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Navigation.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/types/index.ts
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
  src/routes/settings/+layout.svelte
  src/variables.scss
Labels: Missing dev review, QA Tested

#563 add(test): add test attribute for banner
  src/lib/components/ui/InstallBanner.svelte
Labels: Missing dev review, Failed Automated Test

#564 update(relay): new relay for wss
  src/lib/state/wasm/relays.ts
Labels: Missing dev review, QA Tested

#572 feat(chat): Reply UI
  src/lib/lang/en.json
  src/lib/layouts/Chatbar.svelte
Labels: Missing dev review, QA Tested

#576 update(attr): test attrs for sticker emoji and gif picker
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/group/GroupSettings.svelte
  src/lib/components/group/ViewMembers.svelte
  src/lib/components/messaging/CombinedSelector.svelte
  src/lib/components/messaging/emoji/EmojiSelector.svelte
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/profile/ProfilePictureMany.svelte
  src/lib/components/ui/FileUploadButton.svelte
  src/lib/components/ui/PillTabs.svelte
Labels: QA Tested

#581 chore(copy): macOS instead of MacOS
  src/lib/components/ui/InstallBanner.svelte
Labels: Missing dev review

#583 update(App): Change icons to use on MacOS and Windows
  src-tauri/Cargo.lock
  src-tauri/icons/icon.icns
  src-tauri/icons/icon.ico
  src-tauri/icons/icon.png
  vite.config.js
Labels: Ready to Merge

#580 chore(warning): fix warning
  src/lib/layouts/Chatbar.svelte
Labels: Missing dev review, QA Tested

#579 fix(files): fix deleting files from send files
  src/lib/elements/FileUploadPreview.svelte
  src/routes/chat/+page.svelte
Labels: QA Tested

#585 fix(profile): fix profile integration
  src/lib/layouts/Profile.svelte
Labels: Changes Requested

#584 fix(previews): sidebar message previews fix for sent attachments
  src/lib/components/messaging/ChatPreview.svelte
Labels: QA Tested

#600 fix(files): fix path validation for back action
  src/lib/wasm/ConstellationStore.ts
Labels: Ready for Test

#603 chore(docs): add info about mobile
  README.md
Labels: QA Tested

#609 fix(UI): Fix Windows Dropdown Background
  src/app.scss
Labels: Changes Requested

#613 chore(ci): comment apk
  .github/workflows/generate-apk.yml
Labels: QA Tested

#616 fix(Emoji): Let emojis aligned to the left when filtered
  src/lib/components/messaging/emoji/EmojiSelector.svelte
Labels: Missing dev review, QA Tested

#620 chore(ci): update version
  .github/workflows/add-label.yml
Labels: Missing dev review

#622 chore(ci): update version
  .github/workflows/avoid-typos.yml
Labels: Missing dev review

#623 chore(ci): update versions
  .github/workflows/generate-apk.yml
Labels: Missing dev review

#625 chore(ci): update versions
  .github/workflows/run-build.yml
Labels: Missing dev review

#621 chore(ci): update versions
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#626 chore(ci): minor update
  .github/workflows/run-build.yml
Labels: Draft

#627 add(ci): build desktop installers
  .github/workflows/build-desktop.yml
Labels: Missing dev review

#617 fix(Chat): Remove edit when message is sticker or gif
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#598 fix(Mobile): Fixes many UI bugs within mobile resolutions.
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/embeds/FileEmbed.svelte
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/ui/InstallBanner.svelte
  src/lib/components/ui/Swipe.ts
  src/lib/config.ts
  src/lib/enums/icons.ts
  src/lib/lang/en.json
  src/lib/layouts/Sidebar.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/layouts/Topbar.svelte
  src/lib/layouts/login/Entrypoint.svelte
  src/lib/layouts/login/NewAccount.svelte
  src/routes/+layout.svelte
  src/routes/chat/+page.svelte
Labels: Missing fixing conflict, Draft, Failed Automated Test

#573 fix(fontupload): Allow user uploaded fonts and apply
  jsconfig.json
  package.json
  src/lib/state/settings/default.ts
  src/lib/state/ui/index.ts
  src/lib/types/index.ts
  src/routes/+layout.svelte
  src/routes/settings/accessibility/+page.svelte
  src/routes/settings/preferences/+page.svelte
Labels: Missing dev review, QA Tested, Missing fixing conflict, Failed Automated Test

#628 feat(Files): Show chat name and user picture on chat media folders
  src/lib/components/files/FileFolder.svelte
  src/lib/components/profile/ProfilePictureMany.svelte
  src/lib/state/ui/index.ts
  src/lib/types/index.ts
  src/routes/chat/+page.svelte
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
Labels: Missing dev review, Failed Automated Test

#630 Update package.json
  package.json
Labels: Missing dev review, Invalid PR title

#635 chore(ci): fix ci
  .github/workflows/generate-apk.yml
Labels: Missing dev review

#634 chore(build): fix warnings
  src/lib/layouts/Topbar.svelte
Labels: Missing dev review

#636 chore(typo): fix typo asset
  src/lib/enums/icons.ts
  src/lib/layouts/Topbar.svelte
Labels: Missing dev review

#638 fix(ui): fix text appearance
  src/lib/elements/Text.svelte
Labels: Missing dev review, QA Tested, Failed Automated Test

#633 update(ci): update ci to build apps
  .github/workflows/build-desktop.yml
  .github/workflows/create-builds.yml
  .github/workflows/generate-apk.yml
Labels: Draft

#643 fix(Files): Fix toast notification message when create new folders
  src/lib/lang/en.json
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#647 fix(Group): Fix user been kicked from a group when remove a friend
  src/lib/state/Store.ts
Labels: Missing dev review

#646 fix(chat): fix pasting converting emoji when undesired
  src/lib/components/messaging/emoji/EmojiList.ts
  src/lib/layouts/Chatbar.svelte
Labels: QA Tested, Ready to Merge

#649 fix(settings): select background
  src/lib/elements/Select.svelte
Labels: Ready for Test

#648 add(ci): ci to build releases
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-macos.yml
  .github/workflows/build-release-windows.yml
  ui/deb/DEBIAN/control
  ui/deb/DEBIAN/postinst
  ui/deb/usr/share/applications/im.satellite.uplink.desktop
  ui/deb/usr/share/metainfo/im.satellite.uplink.metainfo.xml
Labels: Missing dev review

#640 fix(gifsearch): fix frozen page on gif search
  src/lib/components/messaging/gif/GifSelector.svelte
Labels: QA Tested, Ready to Merge
