Repository Satellite-im/UplinkWeb, pull requests merged in 2024-11, with the labels that each got.

#811 feat(calling): call video select
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/Participant.svelte
  src/lib/media/Voice.ts
Labels: QA Tested, Ready to Merge

#780 feat(calling): add call join button
  src/lib/components/index.ts
  src/lib/components/messaging/message/MessageText.svelte
  src/lib/lang/en.json
  src/lib/media/Voice.ts
  src/lib/mock/messages.ts
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#815 chore(linter): fix linter errors
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/inventory/InventoryItem.svelte
  src/lib/components/ui/RelaySelector.svelte
  src/lib/components/widgets/BatteryIndicator.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/login/RecoveryCopy.svelte
  src/lib/mock/files.ts
  src/lib/mock/inventory.ts
  src/lib/wasm/IWarp.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/settings/about/+page.svelte
  src/routes/settings/preferences/+page.svelte
Labels: being tested

#810 fix(groups): group user list
  src/lib/components/group/ViewMembers.svelte
  src/lib/lang/en.json
Labels: 🔒 blocked, 🫡 Dev Approved Review

#817 fix(Call): Improve talking indicator for video and no video calls
  package.json
  src/lib/components/calling/CallScreen.svelte
  src/lib/media/Voice.ts
Labels: Waiting for CI, 🫡 Dev Approved Review

#822 update(Logger): Add file and line information to log entries when is error or warning
  src/lib/utils/Logger.ts
Labels: Missing dev review, QA Approved

#786 fix(chat): fix group chat perms and modification
  src/lib/components/group/AddMembers.svelte
  src/lib/components/group/GroupSettings.svelte
  src/lib/components/group/ViewMembers.svelte
  src/lib/elements/Button.svelte
  src/lib/lang/en.json
  src/lib/layouts/SettingSection.svelte
  src/lib/types/index.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Approved

#828 chore(task): update versions automatically
  .github/workflows/build-release-android.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-macos.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/zip.yml
  src/lib/components/ui/InstallBanner.svelte
  src/lib/config.ts
  updateVersion.js
Labels: Missing dev review

#829 chore(update): minor update on script
  updateVersion.js
Labels: Missing dev review

#830 chore(version): update logic on naming
  .github/workflows/zip.yml
  updateVersion.js
Labels: Missing dev review

#831 chore(zip): update logic
  .github/workflows/build-release-android.yml
  .github/workflows/zip.yml
Labels: Missing dev review

#832 chore(ci): add ci to update urls
  .github/workflows/update-urls.yml
Labels: Missing dev review

#833 chore(ci): use PowerShell on windows ci
  .github/workflows/build-release-windows.yml
Labels: Missing dev review

#835 chore(ci): remove not needed steps
  .github/workflows/build-release-android.yml
  TODO.md
  updateVersion.js
Labels: Missing dev review

#836 chore(ci): delete not needed ci
  .github/workflows/update-urls.yml
Labels: Missing dev review

#837 chore(ci): update macos ci
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#838 chore(test): test ci
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#839 chore(update): update 2.0.1
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  src/lib/config.ts
Labels: Missing dev review

#841 chore(package): fix package
  src-tauri/Cargo.lock
  src-tauri/tauri.conf.json
Labels: Missing dev review

#842 chore(ci): test
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#843 chore(test): test macos ci
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#844 chore(ci): revert ci
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#813 fix(payments): update ui and verbiage for payment bubbles
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/enums/index.ts
  src/lib/lang/en.json
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/types/index.ts
  src/lib/utils/Wallet.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Approved

#826 chore(profile): delete account
  src/lib/lang/en.json
  src/routes/settings/profile/+page.svelte
Labels: being tested

#827 chore(profile): add support button
  src/lib/enums/icons.ts
  src/lib/lang/en.json
  src/routes/settings/profile/+page.svelte
Labels: being tested

#845 chore(linter): run prettier on the whole code
  .github/workflows/build-release-android.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-macos.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/ios-build.yml
  .github/workflows/run-build.yml
  .github/workflows/zip.yml
  .vscode/extensions.json
  PULL_REQUEST_TEMPLATE.md
  README.md
  TODO.md
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Assets.xcassets/Contents.json
  ios/App/App/Assets.xcassets/Splash.imageset/Contents.json
  scripts/write-commit-hash.cjs
  src-tauri/capabilities/migrated.json
  src-tauri/gen/schemas/acl-manifests.json
  src-tauri/gen/schemas/capabilities.json
  src-tauri/gen/schemas/desktop-schema.json
  src-tauri/gen/schemas/linux-schema.json
  src-tauri/tauri.conf.json
  src/lib/cdn.json
  src/lib/components/ui/InstallBanner.svelte
  src/lib/config.ts
  src/lib/enums/icons.ts
  src/routes/settings/profile/+page.svelte
  static/manifest.json
  svelte.config.js
Labels: Missing dev review, QA Approved

#847 chore(delete): add delete account button on auth page
  src/lib/layouts/login/Unlock.svelte
Labels: Missing dev review, QA Approved

#825 fix(Call): Fix flash talk indicator
  package.json
  src/lib/components/Polling.svelte
  src/lib/components/calling/CallScreen.svelte
  src/lib/media/Voice.ts
  src/lib/wasm/MultipassStore.ts
  vite.config.js
Labels: Missing dev review, QA Approved

#850 feat(profile): add PIN confirmation for account deletion and enhance settings UI
  src/lib/components/PinInput.svelte
  src/lib/lang/en.json
  src/lib/layouts/login/Unlock.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Approved

#851 chore(layout): clean up code and improve event handling in layout components
  src/app.d.ts
  src/custom-events.d.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/wasm/IWarp.ts
  src/routes/+layout.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Approved

#859 chore(link): add ios link on install banner
  src/lib/components/ui/InstallBanner.svelte
  src/lib/config.ts
Labels: Missing dev review

#864 chore(warning): fix warning
  src/lib/layouts/login/NewAccount.svelte
Labels: Missing dev review

#863 feat(Call): Enable screen share on calls.
  src/lib/components/calling/CallScreen.svelte
  src/lib/media/Voice.ts
  src/lib/state/Store.ts
  src/lib/state/initial.ts
Labels: Missing dev review, Failed Automated Test

#866 update(desktop): fix download app banner showing in desktop versions
  src/lib/components/ui/InstallBanner.svelte
Labels: QA Approved

#870 chore(updates): minor update
  ios/App/PluginViewController.swift
  jsconfig.json
  src-tauri/gen/schemas/acl-manifests.json
  src-tauri/gen/schemas/capabilities.json
  src-tauri/gen/schemas/desktop-schema.json
  src/app.html
  src/app.scss
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/files/FileFolder.svelte
  src/lib/components/messaging/Conversation.svelte
  src/lib/components/messaging/embeds/ImageEmbed.svelte
  src/lib/defaults/routes.ts
  src/lib/layouts/login/NewAccount.svelte
  src/lib/state/conversation/index.ts
  src/lib/state/ui/index.ts
  src/lib/state/ui/toast.ts
  src/routes/+page.svelte
  src/routes/community/+layout.svelte
  src/routes/developer/debug/voice/+page.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/notifications/+page.svelte
  src/routes/settings/preferences/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Approved

#861 fix(friend-request): update friendRequestDid regex and adjust request string handling
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/group/GroupSettings.svelte
  src/lib/lang/en.json
  src/lib/utils/CommonInputRules.ts
  src/routes/friends/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: QA Approved, 🫡 Dev Approved Review

#872 feat(ShareScreen): Add live label on screen sharing
  src/lib/components/calling/CallScreen.svelte
  src/lib/lang/en.json
Labels: Missing dev review

#855 fix(CallPopUp): Enable call pop up when user is out of active call chat
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/LiveLabel.svelte
  src/lib/components/calling/VideoPreview.svelte
  src/lib/lang/en.json
  src/lib/media/Voice.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Approved

#875 chore(release): release 2.0.3
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/gen/schemas/acl-manifests.json
  src-tauri/gen/schemas/capabilities.json
  src-tauri/gen/schemas/desktop-schema.json
  src/lib/config.ts
Labels: Missing dev review

#876 chore(ci): remove ci
  .github/workflows/ios-build.yml
Labels: Missing dev review

#891 chore(release): release 2.0.4
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/lib/config.ts
Labels: Missing dev review

#892 chore(update): update versions
  package.json
  src/routes/settings/about/+page.svelte
Labels: 📄 Draft, Failed Automated Test

#885 chore(warning): fix warning on emoji regex
  src/lib/components/utils/Emoji.ts
Labels: Missing dev review, QA Approved

#884 chore(imports): remove not used imports
  src/lib/components/messaging/AttachmentRenderer.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/MessageGroup.svelte
  src/lib/components/ui/GamepadListener.svelte
  src/lib/components/ui/IntegrationDisplay.svelte
  src/lib/components/wallet/Transaction.svelte
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Navigation.svelte
  src/lib/layouts/SettingSection.svelte
  src/lib/wasm/ConstellationStore.ts
  src/routes/+layout.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Approved, Failed Automated Test

#888 chore(warning): fix warning
  src/lib/utils/Notes.ts
Labels: Missing dev review

#887 chore(warning): fix warning
  src/lib/utils/CancellablePromise.ts
Labels: Missing dev review

#890 chore(typo): fix typo
  src/routes/chat/+page.svelte
Labels: Missing dev review

#882 fix(chat): fix dupe users
  src/lib/wasm/RaygunStore.ts
Labels: Missing dev review, QA Approved

#886 chore(fix): fix warning
  src/lib/state/db/persistedState.ts
Labels: Missing dev review, QA Approved

#898 chore(docs): add live reload instructions for mobile development
  README.md
Labels: Missing dev review

#901 chore: (relay) update relays.ts
  src/lib/state/wasm/relays.ts
Labels: Missing dev review, Invalid PR title, Failed Automated Test
