Repository Satellite-im/UplinkWeb, pull requests merged in 2024-10, with the labels that each got.

#650 fix(friends): change friend toast click
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/wasm/MultipassStore.ts
  src/routes/friends/+page.svelte
Labels: QA Tested

#651 update(desktop): universal build for macos and linux setup
  .github/workflows/build-release-linux.yml
  .github/workflows/create-builds.yml
Labels: Missing dev review, Draft

#653 fix(state): retry fetching identity
  src/lib/state/Store.ts
  src/lib/wasm/MultipassStore.ts
Labels: QA Tested

#637 fix(chat): fix markdown editor gone
  src/lib/elements/Input/Input.svelte
  src/routes/chat/+page.svelte
Labels: Missing dev review, Failed Automated Test

#645 fix(ui): update chatbar reply ui
  src/lib/lang/en.json
  src/lib/layouts/Chatbar.svelte
Labels: QA Tested

#659 fix(SeedPhrase): Fix seed phrase when create new account
  src/lib/layouts/login/RecoveryCopy.svelte
  src/routes/auth/+page.svelte
Labels: Missing dev review

#661 chore(seed): download seed
  src/lib/layouts/login/RecoveryCopy.svelte
Labels: Ready to Merge

#660 fix(CreateAccount): Hide import account and change users buttons
  src/lib/layouts/login/Entrypoint.svelte
  src/lib/layouts/login/Unlock.svelte
Labels: Missing dev review, Failed Automated Test

#665 update(ci): run automated tests on docker container
  .github/workflows/automated-tests.yml
Labels: Waiting for CI, Failed Automated Test

#666 update(fix): fix deprecation warnings on build
  vite.config.js
Labels: Missing dev review, QA Tested

#674 chore(test): test
  .github/workflows/auto-add-issues-to-project.yml
Labels: Missing dev review

#565 feat(calling): Group calling
  package.json
  src/lib/components/calling/CallControls.svelte
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/CallSettings.svelte
  src/lib/components/calling/IncomingCall.svelte
  src/lib/components/settings/VideoTest.svelte
  src/lib/layouts/Navigation.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/media/Voice.ts
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/routes/+layout.svelte
  src/routes/chat/+page.svelte
  src/routes/developer/debug/voice/+page.svelte
  src/routes/settings/audio_video/+page.svelte
  vite.config.js
Labels: Missing dev review

#678 feat(dev): improve logging
  src/lib/utils/Logger.ts
Labels: QA Tested, Ready to Merge

#686 chore(relay): fix warning
  src/lib/components/ui/RelaySelector.svelte
Labels: Missing dev review, QA Tested

#687 chore(settings): add error message relay
  src/lib/components/ui/RelaySelector.svelte
  src/lib/lang/en.json
Labels: Missing dev review, QA Tested

#682 chore(attachments): create attachments component to alleviate duplicate code
  src/lib/components/messaging/AttachmentRenderer.svelte
  src/routes/chat/+page.svelte
Labels: QA Tested

#708 fix(gifs): reply preview for gifs extra large
  src/lib/layouts/Chatbar.svelte
Labels: QA Tested, Ready to Merge

#695 fix(multipass): add missing multipass event
  src/lib/wasm/MultipassStore.ts
Labels: QA Tested, Ready to Merge

#689 fix(chat): update emoji picker
  src/lib/components/messaging/emoji/EmojiSelector.svelte
  src/lib/state/ui/index.ts
Labels: QA Tested, Failed Automated Test

#712 update(ci): publish playwright and allure report
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#696 fix(call): Fix video feed not appearing
  src/lib/components/calling/CallScreen.svelte
  src/lib/lang/en.json
  src/lib/media/Voice.ts
Labels: Missing dev review, QA Tested

#714 fix(Emojis): Maximum emojis to react is 6
  src/lib/state/ui/index.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review

#711 fix(IncomingCall): Improve spaces when status message is empty on IncomingCall component
  src/lib/components/calling/IncomingCall.svelte
Labels: Missing dev review, QA Tested

#697 feat(Call): Add feedback when there is no answer from other user
  src/lib/components/calling/CallScreen.svelte
  src/lib/lang/en.json
  src/lib/media/Voice.ts
Labels: Missing dev review, QA Tested

#699 feat(call): Add better UI to show if user is inviting for a group call
  src/lib/components/calling/IncomingCall.svelte
  src/lib/lang/en.json
Labels: Missing dev review, QA Tested

#703 feat(Call): Add option to answer call with video or just audio
  src/lib/components/calling/IncomingCall.svelte
  src/lib/lang/en.json
Labels: Missing dev review, QA Tested

#725 chore(ci): use the same comment on the bot
  .github/workflows/lint-pr-title.yml
Labels: QA Tested

#726 chore(ci): update ci
  .github/workflows/run-build.yml
Labels: Waiting for CI

#728 fix(loggings): update log thing
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/utils/Logger.ts
Labels: Missing dev review, Failed Automated Test

#732 update(ci): fix publish report bug
  .github/workflows/automated-tests.yml
Labels: QA Tested, Waiting for CI

#704 feat(chat): impl file sharing chat
  src/lib/components/files/ShareFile.svelte
  src/lib/components/messaging/AttachmentRenderer.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/embeds/FileEmbed.svelte
  src/lib/lang/en.json
  src/routes/chat/+page.svelte
Labels: QA Tested

#713 feat(Call): Wire up call volumes
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/VolumeMixer.svelte
  src/lib/elements/RangeSelector.svelte
  src/lib/media/Voice.ts
  src/lib/state/Store.ts
  src/lib/types/index.ts
Labels: Missing dev review, QA Tested

#720 update(tauri): upgrate tauri to v2
  .github/workflows/build-release-linux.yml
  .github/workflows/create-builds.yml
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/capabilities/migrated.json
  src-tauri/gen/schemas/acl-manifests.json
  src-tauri/gen/schemas/capabilities.json
  src-tauri/gen/schemas/desktop-schema.json
  src-tauri/gen/schemas/linux-schema.json
  src-tauri/tauri.conf.json
Labels: Missing dev review, QA Tested, Failed Automated Test

#737 fix(Call): Fix call feedback
  src/lib/components/calling/CallScreen.svelte
Labels: Missing dev review, QA Tested

#741 feat(chat): clickable unread bar
  src/lib/components/messaging/Conversation.svelte
Labels: QA Tested, Ready to Merge

#743 fix(ui): update incoming call ui
  src/lib/components/calling/IncomingCall.svelte
  src/lib/lang/en.json
Labels: QA Tested, Ready to Merge

#747 update(CallScreen): Sort chat users by video enabled status
  src/lib/components/calling/CallScreen.svelte
Labels: Missing dev review, QA Tested

#751 chore(ci): update version
  .github/workflows/avoid-typos.yml
Labels: Missing dev review

#753 chore(ci): update version
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#754 chore(ci): update version
  .github/workflows/build-release-windows.yml
Labels: Missing dev review

#750 chore(ci): update version
  .github/workflows/automated-tests.yml
Labels: QA Tested, Waiting for CI

#752 chore(ci): update version
  .github/workflows/build-release-linux.yml
Labels: QA Tested, Waiting for CI

#755 chore(ci): update version
  .github/workflows/create-builds.yml
Labels: QA Tested, Waiting for CI

#758 chore(docs): update docs
  README.md
Labels: Missing dev review

#776 add(attributes): adding test attributes for some elements
  src/lib/components/calling/IncomingCall.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/Conversation.svelte
  src/lib/layouts/Chatbar.svelte
Labels: Missing dev review

#768 update(Log): Improve logs on console
  src/lib/utils/Logger.ts
  src/lib/wasm/MultipassStore.ts
Labels: Missing dev review, QA Tested

#782 update(ci): increase retention days for test artifacts
  .github/workflows/automated-tests.yml
Labels: Missing dev review, Failed Automated Test

#781 chore(assets): remove all x1 assets
  ios/App/App/Assets.xcassets/AppIcon.appiconset/102.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/128.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/16.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/20.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/29.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/50.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/57.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/72.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/76.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Missing dev review, QA Tested

#779 chore(group): add empty state
  src/lib/components/group/CreateGroup.svelte
  src/lib/lang/en.json
Labels: Missing dev review, QA Tested

#783 chore(mobile): add new splash screen from capacitor
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
Labels: Missing dev review, QA Tested

#785 update(ci): draft for improving automation publish report
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#789 chore(release): add gh release steps on build workflows
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-macos.yml
  .github/workflows/build-release-windows.yml
Labels: Missing dev review

#792 add(ci): build releases for android and ios
  .github/workflows/build-release-android.yml
  .github/workflows/build-release-ios.yml
Labels: Draft

#791 chore(ios): ios stuff
  .github/workflows/ios-build.yml
  ios/App/ExportOptions.plist
  ios/App/Podfile.lock
Labels: Draft

#793 chore(version): update version to 2.0.0
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  src/lib/config.ts
Labels: being tested

#795 chore(urls): update urls
  src/lib/config.ts
Labels: Missing dev review

#797 fix(call): retry connection instead of wait if not made
  src/lib/media/Voice.ts
Labels: Missing dev review, QA Tested

#799 chore(ci): add zip bot
  .github/workflows/zip.yml
Labels: Draft

#800 chore(ci): fix permissions
  .github/workflows/zip.yml
Labels: Missing dev review

#801 chore(ci): update file name
  .github/workflows/zip.yml
Labels: Missing dev review

#796 fix(calling): loop incoming/outgoing callsound
  src/lib/components/calling/CallScreen.svelte
  src/lib/components/calling/IncomingCall.svelte
Labels: Missing dev review, QA Tested

#802 chore(ci): update ci
  .github/workflows/build-release-android.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-macos.yml
  .github/workflows/build-release-windows.yml
Labels: Draft

#784 chore(groups): deactivate button if there are no users on list
  src/lib/components/group/CreateGroup.svelte
Labels: Missing dev review, QA Tested, Failed Automated Test

#777 feat(Call): Implement push to talk
  src/lib/components/calling/CallScreen.svelte
Labels: Missing dev review, QA Tested

#803 chore(ci): update versions
  .github/workflows/zip.yml
Labels: Missing dev review

#805 chore(ci): update versions
  .github/workflows/build-release-ios.yml
Labels: Missing dev review

#804 chore(ci): update versions
  .github/workflows/build-release-android.yml
Labels: Missing dev review

#806 chore(ci): update versions
  .github/workflows/build-release-linux.yml
Labels: Missing dev review

#807 chore(ci): update versions
  .github/workflows/build-release-windows.yml
Labels: Missing dev review

#808 chore(ci): update versions
  .github/workflows/build-release-macos.yml
Labels: Missing dev review

#809 chore(ci): update versions
  .github/workflows/create-builds.yml
Labels: Missing dev review
