Repository Satellite-im/UplinkWeb, pull requests merged in 2024-07, with the labels that each got.

#145 feat(GIF Selector): Adds a GIF selector to the application using Giphy.
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/CombinedSelector.svelte
  src/lib/components/messaging/emoji/EmojiSelector.svelte
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/ui/CDNConfigurator.svelte
  src/lib/components/ui/PillTabs.svelte
  src/lib/config.ts
  src/lib/elements/Button.svelte
  src/lib/enums/icons.ts
  src/lib/keys.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/mock/users.ts
  src/lib/types/index.ts
  src/routes/chat/+page.svelte
  src/routes/settings/network/+page.svelte
Labels: Draft

#180 Stickers
  src/lib/components/messaging/CombinedSelector.svelte
  src/lib/components/messaging/emoji/EmojiSelector.svelte
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/components/ui/ContextMenu.svelte
  src/lib/components/widgets/BatteryIndicator.svelte
  src/lib/components/widgets/CPU.svelte
  src/lib/components/widgets/RamUsage.svelte
  src/lib/components/widgets/WidgetBar.svelte
  src/lib/config.ts
  src/lib/enums/icons.ts
  src/lib/lang/index.ts
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/state/conversation/index.ts
  src/lib/state/settings/default.ts
  src/lib/state/settings/index.ts
  src/lib/state/wasm/relays.ts
  src/lib/types/index.ts
  src/routes/developer/debug/voice/+page.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/preferences/+page.svelte
  static/assets/stickers/manifest.json
  static/assets/stickers/space_cat/1.png
  static/assets/stickers/space_cat/10.png
  static/assets/stickers/space_cat/11.png
  static/assets/stickers/space_cat/12.png
  static/assets/stickers/space_cat/13.png
  static/assets/stickers/space_cat/14.png
  static/assets/stickers/space_cat/15.png
  static/assets/stickers/space_cat/16.png
  static/assets/stickers/space_cat/17.png
  static/assets/stickers/space_cat/18.png
  static/assets/stickers/space_cat/2.png
  static/assets/stickers/space_cat/3.png
  static/assets/stickers/space_cat/4.png
  static/assets/stickers/space_cat/5.png
  static/assets/stickers/space_cat/6.png
  static/assets/stickers/space_cat/7.png
  static/assets/stickers/space_cat/8.png
  static/assets/stickers/space_cat/9.png
Labels: Missing dev review, Invalid PR title

#173 fix(Constellation): Fix delete files from storage
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#172 feat(UI): Add way to erase profile and banner pictures
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#154 feat(logger): add logger level setting
  src/lib/utils/Logger.ts
  src/routes/settings/developer/+page.svelte
Labels: Missing dev review, QA Tested, Missing fixing conflict

#155 fix(input): fixed number on input to change fontSize
  src/lib/elements/Input/Input.svelte
  src/routes/settings/preferences/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#152 feat(download): add file size
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#175 fix(CreateAccount): Create input Rules for username
  src/lib/elements/Input/Input.svelte
  src/lib/elements/Input/inputRules.ts
  src/routes/auth/new_account/+page.svelte
Labels: Missing dev review

#179 update(Profile): Apply rule to username on profile page
  src/lib/elements/Input/Input.svelte
  src/lib/elements/Input/inputRules.ts
  src/lib/utils/CommonInputRules.ts
  src/routes/auth/new_account/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing fixing conflict, Ready for Test

#182 Hotfix 4
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/ui/RelaySelector.svelte
  src/lib/utils/CommonInputRules.ts
  src/lib/utils/Result.ts
  src/routes/+layout.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, Invalid PR title

#184 stuff
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/messaging/stickers/manifest.json
  src/variables.scss
  static/assets/stickers/bad_animals/taxes.png
Labels: Missing dev review, Invalid PR title

#186 update(fix): text out of bounds in chatbar
  src/lib/elements/Input/Input.svelte
  src/lib/elements/Input/markdown.scss
Labels: Missing dev review, QA Tested

#193 add(Icons): Ram and Sticker Icons
  src/lib/enums/icons.ts
Labels: Missing fixing conflict

#185 feat(dependency): update markdown editor lib
  package-lock.json
  package.json
Labels: Missing dev review, QA Tested

#187 update(Friend): Create toast message for friend request and delete modals
  src/lib/elements/Toast.svelte
  src/lib/layouts/Sidebar.svelte
  src/lib/state/ui/toast.ts
  src/lib/utils/CommonInputRules.ts
  src/routes/auth/new_account/+page.svelte
  src/routes/friends/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#198 Hotfix 5
  src/lib/components/messaging/gif/GifSelector.svelte
  src/lib/components/messaging/stickers/StickerSelector.svelte
  src/lib/components/messaging/stickers/manifest.json
  src/lib/layouts/Chatbar.svelte
  src/variables.scss
  static/assets/stickers/fishy_business/accounting.png
  static/assets/stickers/fishy_business/akakakakak.png
  static/assets/stickers/fishy_business/busy.png
  static/assets/stickers/fishy_business/elevator.png
  static/assets/stickers/fishy_business/onholiday.png
  static/assets/stickers/fishy_business/puffercall.png
  static/assets/stickers/fishy_business/stonkbad.png
  static/assets/stickers/garden/angrymower.png
  static/assets/stickers/garden/smelly.png
  static/assets/stickers/garden/wilted.png
  static/assets/stickers/words/depression.png
  static/assets/stickers/words/iloveu.png
Labels: Missing dev review, Invalid PR title

#197 fix(Button): Fixed highlighted decrease button on font size
  src/routes/settings/preferences/+page.svelte
Labels: Missing dev review, QA Tested

#177 update(Input): All text selected on Input with one click
  src/lib/elements/Input/Input.svelte
Labels: Missing dev review, QA Tested

#195 update(Input): Block action buttons if input text does not follow input rules
  src/routes/auth/new_account/+page.svelte
  src/routes/friends/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#199 chore(typo): fix typo
  src/lib/types/index.ts
Labels: Missing dev review

#200 fix(chat): fix undefined usernames in chat
  src/lib/wasm/MultipassStore.ts
Labels: Waiting for CI

#201 fix(copydid): copy did by default instead of short id
  src/routes/friends/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Waiting for CI

#202 fix(Profile): Always compress image to be possible to upload it to profile picture or banner picture
  src/lib/components/ui/FileUploadButton.svelte
  src/lib/components/utils/CompressImage.ts
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#214 fix(Profile): Fix undefined status message and username on profile page
  src/routes/+layout.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#220 fix(Keybinds): Fix keybinds not saving properly.
  src/lib/components/settings/Key.svelte
  src/lib/components/ui/KeyboardListener.svelte
  src/routes/settings/keybinds/+page.svelte
Labels: Missing dev review, Ready for Test

#211 fix(Input): Clear input when rich option is enabled and we click on send button
  src/lib/elements/Input/Input.svelte
Labels: Missing dev review, QA Tested

#221 feat(Gamepad): Adds basic gamepad support, required devmode enabled for now.
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/stickers/manifest.json
  src/lib/components/ui/GamepadListener.svelte
  src/lib/elements/Select.svelte
  src/lib/enums/index.ts
  src/routes/+layout.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/gamepad/+page.svelte
  static/assets/controller/ps5/circle.png
  static/assets/controller/ps5/controller.png
  static/assets/controller/ps5/controller_off.png
  static/assets/controller/ps5/dpad-down.png
  static/assets/controller/ps5/dpad-left.png
  static/assets/controller/ps5/dpad-right.png
  static/assets/controller/ps5/dpad-up.png
  static/assets/controller/ps5/l3.png
  static/assets/controller/ps5/left-stick.png
  static/assets/controller/ps5/menu.png
  static/assets/controller/ps5/options.png
  static/assets/controller/ps5/psbutton.png
  static/assets/controller/ps5/r3.png
  static/assets/controller/ps5/right-stick.png
  static/assets/controller/ps5/square.png
  static/assets/controller/ps5/touchpad.png
  static/assets/controller/ps5/triangle.png
  static/assets/controller/ps5/x.png
  static/assets/controller/virtual_cursor.png
  static/assets/controller/virtual_cursor_hover.png
Labels: Missing dev review

#222 updata(patch): patch
  src/lib/components/Polling.svelte
  src/lib/components/index.ts
  src/lib/components/ui/AAR.svelte
  src/lib/components/ui/GamepadListener.svelte
  src/routes/settings/developer/+page.svelte
  src/routes/settings/gamepad/+page.svelte
  static/assets/arrow.png
Labels: Missing dev review, Invalid PR title

#213 fix(lib): update markdown editor lib
  package-lock.json
  package.json
Labels: Missing dev review, Changes Requested

#212 feat(login): Login rework
  src/lib/enums/index.ts
  src/lib/lang/index.ts
  src/lib/layouts/login/Entrypoint.svelte
  src/lib/layouts/login/NewAccount.svelte
  src/lib/layouts/login/RecoveryCopy.svelte
  src/lib/layouts/login/Unlock.svelte
  src/lib/layouts/login/index.ts
  src/lib/wasm/IWarp.ts
  src/lib/wasm/TesseractStore.ts
  src/lib/wasm/WarpStore.ts
  src/routes/+layout.svelte
  src/routes/auth/+page.svelte
Labels: question, Missing dev review

#223 fix(relay): remove debug address
  src/lib/wasm/WarpStore.ts
Labels: Missing dev review

#219 fix(Keybinds): Fix option on keybinds and show normal Key
  src/lib/components/ui/KeyboardListener.svelte
Labels: Missing dev review

#226 chore(playwright): add automated tests for playwright
  .github/workflows/automated-tests.yml
Labels: Missing dev review, QA Tested

#227 feat(sounds): Sound rework
  package-lock.json
  package.json
  src/lib/components/utils/SoundHandler.ts
  src/lib/components/utils/Sounds.ts
  src/lib/state/Store.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/+layout.svelte
Labels: Missing dev review, QA Tested

#235 fix(login): update create account description
  src/lib/lang/index.ts
Labels: Missing dev review, QA Tested

#225 feat(Friends): Add users profile pictures
  package-lock.json
  package.json
  src/lib/components/Polling.svelte
  src/lib/components/friends/Friend.svelte
  src/lib/wasm/MultipassStore.ts
  src/routes/settings/profile/+page.svelte
Labels: QA Tested

#238 update(Chats): Update users on Chats
  src/lib/components/Polling.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/wasm/MultipassStore.ts
  src/routes/chat/+page.svelte
Labels: Missing dev review, QA Tested

#233 feat(PFP): Fallback identicons for profiles without a picture
  package-lock.json
  package.json
  src/lib/components/calling/Participant.svelte
  src/lib/components/friends/Friend.svelte
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/group/ViewMembers.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/messaging/CombinedSelector.svelte
  src/lib/components/profile/ProfilePicture.svelte
  src/lib/components/profile/ProfilePictureMany.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/components/ui/FileUploadButton.svelte
  src/lib/components/ui/GamepadListener.svelte
  src/lib/components/ui/KeyboardListener.svelte
  src/lib/enums/icons.ts
  src/lib/layouts/Profile.svelte
  src/lib/layouts/Slimbar.svelte
  src/routes/+layout.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/profile/+page.svelte
  src/routes/wallet/+page.svelte
Labels: QA Tested

#245 fix(Profile): Fix update username and status message at same time
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#239 feat(login): wire up passphrase creation
  src/lib/wasm/MultipassStore.ts
  src/routes/auth/+page.svelte
Labels: Missing dev review, QA Tested

#237 fix(chat): Fix message text overflowing
  src/lib/components/messaging/message/Message.svelte
Labels: Missing dev review, QA Tested

#236 fix(multipass): make log print enum name instead of ordinal
  src/lib/wasm/MultipassStore.ts
Labels: Missing dev review, QA Tested

#252 fix(Profile): Clear profile picture and back to default one
  src/lib/components/ui/ContextMenu.svelte
  src/lib/types/index.ts
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#258 fix(CreateAccount): Let profile picture on create account as default
  src/lib/layouts/login/NewAccount.svelte
Labels: Missing dev review, QA Tested

#266 fix(Conversations): Fix conversations breaking after refresh
  src/lib/wasm/RaygunStore.ts
Labels: QA Tested, Ready to Merge

#255 fix(Picture): Show profile picture when user erase its own picture
  src/lib/wasm/MultipassStore.ts
Labels: Missing dev review, QA Tested

#261 feat(store): User cache
  src/lib/components/friends/Friend.svelte
  src/lib/components/group/CreateGroup.svelte
  src/lib/components/messaging/ChatPreview.svelte
  src/lib/components/ui/ChatFilter.svelte
  src/lib/components/utils/StoreResolver.svelte
  src/lib/components/wallet/Transaction.svelte
  src/lib/elements/Input/Input.svelte
  src/lib/layouts/Profile.svelte
  src/lib/layouts/Slimbar.svelte
  src/lib/mock/messages.ts
  src/lib/mock/users.ts
  src/lib/mock/wallet.ts
  src/lib/state/Store.ts
  src/lib/state/initial.ts
  src/lib/types/index.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/chat/+page.svelte
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Tested

#267 fix(SeedPhrase): Show same seed phrase on new account and profile
  src/lib/state/auth/index.ts
  src/routes/auth/+page.svelte
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, QA Tested

#279 fix(Files): Fix upload files with same name
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#262 fix(Friends): Fix buttons on top of friends page
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Tested

#269 fix(Files): Fix rename files and toast notification
  src/lib/components/files/FileFolder.svelte
  src/routes/files/+page.svelte
  src/routes/files/FolderItem.svelte
Labels: Missing dev review, QA Tested

#263 update(NewAccount): Add possibility to add profile picture when user is creating account
  src/lib/layouts/login/NewAccount.svelte
  src/lib/wasm/MultipassStore.ts
  src/routes/auth/+page.svelte
Labels: Missing dev review, QA Tested

#282 chore(ci): add summary test results comment on PR
  .github/workflows/automated-tests.yml
Labels: Missing dev review

#284 fix(regression): conversation.id is not a function
  src/lib/wasm/RaygunStore.ts
Labels: Missing dev review

#286 fix(cache): fix cache return undef
  src/lib/state/Store.ts
Labels: Missing dev review, QA Tested

#285 fix(CreateNewAccount): Fix UI on create new account
  package-lock.json
  src/lib/layouts/Controls.svelte
  src/lib/layouts/login/Entrypoint.svelte
Labels: Missing dev review, QA Tested

#291 fix(format): Fix format flip flop
  .vscode/extensions.json
  .vscode/settings.json
  src/lib/components/ui/ContextMenu.svelte
  src/lib/components/utils/CheckBrowser.ts
  src/lib/components/utils/CompressImage.ts
  src/lib/components/widgets/BatteryIndicator.svelte
  src/lib/components/widgets/RamUsage.svelte
  src/lib/config.ts
  src/lib/enums/index.ts
  src/lib/keys.ts
  src/lib/lang/index.ts
  src/lib/layouts/Controls.svelte
  src/lib/layouts/login/NewAccount.svelte
  src/lib/mock/inventory.ts
  src/lib/state/settings/default.ts
  src/lib/types/index.ts
  src/lib/utils/Wallet.ts
  src/lib/wasm/MultipassStore.ts
  src/lib/wasm/RaygunStore.ts
  src/routes/files/+page.svelte
  src/routes/friends/+page.svelte
Labels: Missing dev review, QA Tested

#294 chore(ci): remove cypress job from automated tests
  .github/workflows/automated-tests.yml
Labels: Missing dev review, QA Tested

#296 refactor(Auth): Change standard value for stayLoggedIn to true
  src/lib/components/PinInput.svelte
  src/lib/state/auth/index.ts
  src/routes/+layout.svelte
Labels: Changes Requested

#306 chore(reporter): update JSON report to be posted on failure
  .github/workflows/automated-tests.yml
Labels: QA Tested

#305 update(Files): Adjust max storage size and let free space automatically
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/routes/files/+page.svelte
Labels: Missing dev review, QA Tested

#273 fix(files): remove sortable and add drag and drop files and folders
  src/lib/wasm/ConstellationStore.ts
  src/lib/wasm/HandleWarpErrors.ts
  src/routes/files/+page.svelte
Labels: QA Tested, Missing fixing conflict

#301 fix(auth): fix problem with auto login/refresh
  src/lib/state/auth/index.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/auth/+page.svelte
Labels: Missing dev review

#307 chore(Mobile): Fix mobile resolution bugs.
  src/lib/layouts/Chatbar.svelte
  src/lib/layouts/Sidebar.svelte
Labels: Missing dev review, QA Tested, Missing fixing conflict

#323 feat(profile-metadata): store profile metadata in warp
  package.json
  src/lib/components/ui/IntegrationDisplay.svelte
  src/lib/components/widgets/BatteryIndicator.svelte
  src/lib/lang/index.ts
  src/lib/layouts/Profile.svelte
  src/lib/state/Store.ts
  src/lib/types/index.ts
  src/lib/utils/ProfileUtils.ts
  src/lib/wasm/MultipassStore.ts
  src/routes/settings/profile/+page.svelte
Labels: Missing dev review, Changes Requested
